#!/usr/bin/env python3
"""
Text2Game - 游戏生成器
基于分析结果生成Godot游戏项目
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional

# 导入子生成器
def _load_generator(module_name: str, class_name: str):
    """动态加载生成器模块"""
    try:
        mod = __import__(f"generators.{module_name}", fromlist=[class_name])
        return getattr(mod, class_name)
    except ImportError:
        import importlib.util
        _spec = importlib.util.spec_from_file_location(
            module_name,
            Path(__file__).parent / "generators" / f"{module_name}.py"
        )
        if _spec and _spec.loader:
            _mod = importlib.util.module_from_spec(_spec)
            _spec.loader.exec_module(_mod)
            return getattr(_mod, class_name, None)
    return None

VisualNovelGenerator = _load_generator("visual_novel", "VisualNovelGenerator")
TwineGenerator = _load_generator("twine", "TwineGenerator")

# 支持的游戏类型
SUPPORTED_TYPES = ["rpg", "adventure", "visual_novel", "strategy", "action", "twine"]

# 默认配置
DEFAULT_OUTPUT_DIR = "./generated_games"


class GameGenerator:
    """游戏生成器"""
    
    def __init__(self, output_dir: str = DEFAULT_OUTPUT_DIR):
        self.output_dir = Path(output_dir)
    
    def generate_game(self, analysis_file: str, game_type: str, game_config: Optional[Dict] = None, use_llm: bool = True) -> str:
        """生成游戏"""
        # Twine 类型使用专用生成器
        if game_type == "twine" and TwineGenerator is not None:
            print("使用 Twine/Chapbook 故事生成器...")
            generator = TwineGenerator(str(self.output_dir))
            return generator.generate(analysis_file, use_llm=use_llm)
        
        # 视觉小说类型使用专用生成器
        if game_type == "visual_novel" and VisualNovelGenerator is not None:
            print("使用视觉小说专用生成器...")
            generator = VisualNovelGenerator(str(self.output_dir))
            return generator.generate(analysis_file, use_llm=use_llm)
        
        # 读取分析结果
        analysis_path = Path(analysis_file)
        if not analysis_path.exists():
            raise FileNotFoundError(f"分析文件不存在: {analysis_file}")
        
        analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
        
        # 获取游戏名称
        game_name = self._generate_game_name(analysis, game_type)
        project_path = self.output_dir / game_name
        
        print(f"正在生成游戏: {game_name}")
        print(f"游戏类型: {game_type}")
        print(f"输出路径: {project_path}")
        
        # 创建项目结构
        self._create_project_structure(project_path)
        
        # 生成项目配置
        self._create_project_godot(project_path, analysis, game_type)
        
        # 生成主场景
        self._create_main_scene(project_path, analysis, game_type)
        
        # 生成游戏逻辑
        self._create_game_logic(project_path, analysis, game_type)
        
        # 生成主脚本
        self._create_main_script(project_path, analysis, game_type)
        
        # 生成游戏场景
        self._create_game_scene(project_path, analysis, game_type)
        
        # 生成游戏场景脚本
        self._create_game_scene_script(project_path, analysis, game_type)
        
        # 生成角色系统
        self._create_character_system(project_path, analysis)
        
        # 生成对话系统
        self._create_dialogue_system(project_path, analysis)
        
        # 保存分析数据
        self._save_analysis_data(project_path, analysis, game_type)
        
        print(f"\n✓ 游戏生成完成!")
        print(f"使用以下命令运行游戏:")
        print(f"  godot --path {project_path}")
        
        return str(project_path)
    
    def _generate_game_name(self, analysis: Dict, game_type: str) -> str:
        """生成游戏名称"""
        # 尝试从分析结果获取名称
        world = analysis.get("analysis", {}).get("world", {})
        if world.get("name"):
            name = world["name"]
        else:
            name = "GeneratedGame"
        
        # 清理名称
        name = "".join(c for c in name if c.isalnum() or c in "_- ")
        name = name.replace(" ", "_")
        
        # 添加类型后缀
        return f"{name}_{game_type}"
    
    def _create_project_structure(self, project_path: Path) -> None:
        """创建项目目录结构"""
        dirs = [
            "",
            "scenes",
            "scripts",
            "scripts/scenes",
            "resources",
            "resources/fonts",
            "resources/images",
            "resources/music",
            "resources/sounds",
            "data"
        ]
        
        for dir_name in dirs:
            (project_path / dir_name).mkdir(parents=True, exist_ok=True)
        
        print("✓ 项目结构创建完成")
    
    def _create_project_godot(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建project.godot"""
        game_info = analysis.get("analysis", {}).get("world", {})
        title = game_info.get("name", "Generated Game")
        
        content = f"""; Engine configuration file.
; Generated by Text2Game

config_version=5

[application]

config/name="{title}"
config/description="由Text2Game生成的游戏"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.7", "GL Compatibility")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
"""
        
        (project_path / "project.godot").write_text(content, encoding="utf-8")
        print("✓ project.godot 创建完成")
    
    def _create_main_scene(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建主场景"""
        scene_content = """[gd_scene load_steps=2 format=3 uid="uid://main"]

[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]

[node name="Main" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
script = ExtResource("1_main")

[node name="Background" type="ColorRect" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
color = Color(0.1, 0.1, 0.15, 1)

[node name="VBoxContainer" type="VBoxContainer" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
offset_left = 40.0
offset_top = 40.0
offset_right = -40.0
offset_bottom = -40.0

[node name="Title" type="Label" parent="VBoxContainer"]
layout_mode = 2
text = "游戏标题"
horizontal_alignment = 1
theme_override_font_sizes/font_size = 32

[node name="Content" type="RichTextLabel" parent="VBoxContainer"]
layout_mode = 2
size_flags_vertical = 3
bbcode_enabled = true

[node name="ButtonContainer" type="HBoxContainer" parent="VBoxContainer"]
layout_mode = 2
alignment = 1

[node name="StartButton" type="Button" parent="VBoxContainer/ButtonContainer"]
layout_mode = 2
text = "开始游戏"
"""
        
        (project_path / "scenes" / "main.tscn").write_text(scene_content, encoding="utf-8")
        print("✓ 主场景创建完成")
    
    def _create_main_script(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建主脚本"""
        script_content = '''## 主场景控制器
extends Control

## 系统引用
var game_logic: Node
var dialogue_system: Node
var character_system: Node

## 组件引用
@onready var title_label = $VBoxContainer/Title
@onready var content_label = $VBoxContainer/Content
@onready var start_button = $VBoxContainer/ButtonContainer/StartButton

func _ready() -> void:
	# 初始化系统
	character_system = preload("res://scripts/character_system.gd").new()
	add_child(character_system)
	
	dialogue_system = preload("res://scripts/dialogue_system.gd").new()
	add_child(dialogue_system)
	
	game_logic = preload("res://scripts/game_logic.gd").new()
	add_child(game_logic)
	
	# 连接信号
	dialogue_system.dialogue_started.connect(_on_dialogue_started)
	dialogue_system.dialogue_ended.connect(_on_dialogue_ended)
	
	# 初始化UI
	title_label.text = "游戏"
	content_label.text = "欢迎来到游戏世界！"
	
	# 连接按钮
	start_button.pressed.connect(_on_start_button_pressed)

func _on_start_button_pressed() -> void:
	# 开始游戏
	game_logic.change_scene("game")

func _on_dialogue_started(speaker: String, text: String) -> void:
	content_label.text = "[b]%s[/b]\n%s" % [speaker, text]

func _on_dialogue_ended() -> void:
	content_label.text = "游戏结束"
'''
        
        (project_path / "scripts" / "main.gd").write_text(script_content, encoding="utf-8")
        print("✓ 主脚本创建完成")
    
    def _create_game_scene(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建游戏场景"""
        scene_content = '''[gd_scene load_steps=2 format=3 uid="uid://game_scene"]

[ext_resource type="Script" path="res://scripts/game_scene.gd" id="1_script"]

[node name="Game" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
script = ExtResource("1_script")

[node name="Background" type="ColorRect" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
color = Color(0.08, 0.08, 0.12, 1)

[node name="VBoxContainer" type="VBoxContainer" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
offset_left = 40.0
offset_top = 40.0
offset_right = -40.0
offset_bottom = -40.0

[node name="SpeakerLabel" type="Label" parent="VBoxContainer"]
layout_mode = 2
text = ""
theme_override_font_sizes/font_size = 24
theme_override_colors/font_color = Color(0.9, 0.9, 1.0, 1)

[node name="DialogueBox" type="PanelContainer" parent="VBoxContainer"]
layout_mode = 2
size_flags_vertical = 3

[node name="VBox" type="VBoxContainer" parent="VBoxContainer/DialogueBox"]
layout_mode = 2

[node name="TextLabel" type="RichTextLabel" parent="VBoxContainer/DialogueBox/VBox"]
layout_mode = 2
size_flags_vertical = 3
bbcode_enabled = true
text = ""

[node name="ChoicesContainer" type="VBoxContainer" parent="VBoxContainer"]
layout_mode = 2

[node name="ContinueButton" type="Button" parent="VBoxContainer"]
layout_mode = 2
text = "继续"
custom_minimum_size = Vector2(200, 40)
'''
        
        (project_path / "scenes" / "game.tscn").write_text(scene_content, encoding="utf-8")
        print("✓ 游戏场景创建完成")
    
    def _create_game_scene_script(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建游戏场景脚本"""
        script_content = '''## 游戏场景控制器
extends Control

## 组件引用
@onready var speaker_label = $VBoxContainer/SpeakerLabel
@onready var text_label = $VBoxContainer/DialogueBox/VBox/TextLabel
@onready var choices_container = $VBoxContainer/ChoicesContainer
@onready var continue_button = $VBoxContainer/ContinueButton

## 系统引用
var dialogue_system: Node
var character_system: Node
var game_logic: Node

## 当前对话数据
var current_dialogues: Array = []
var current_index: int = 0

func _ready() -> void:
	# 获取系统引用
	dialogue_system = _find_system("DialogueSystem")
	character_system = _find_system("CharacterSystem")
	game_logic = _find_system("GameLogic")
	
	# 连接信号
	continue_button.pressed.connect(_on_continue_pressed)
	
	if dialogue_system:
		dialogue_system.dialogue_started.connect(_on_dialogue_started)
		dialogue_system.dialogue_ended.connect(_on_dialogue_ended)
	
	# 开始游戏
	_start_game()

func _find_system(system_name: String) -> Node:
	for child in get_parent().get_children():
		if child.get_script() and child.get_script().get_global_name() == system_name:
			return child
	for child in get_children():
		if child.get_script() and child.get_script().get_global_name() == system_name:
			return child
	return null

func _start_game() -> void:
	_load_dialogues()
	
	speaker_label.text = "旁白"
	text_label.text = "欢迎来到游戏世界!\n\n点击[继续]开始冒险..."
	continue_button.visible = true

func _load_dialogues() -> void:
	var file = FileAccess.open("user://data/game_config.json", FileAccess.READ)
	if file:
		var json = JSON.new()
		var result = json.parse(file.get_as_text())
		if result == OK:
			var config_data = json.data
			current_dialogues = config_data.get("dialogues", {}).get("main", [])
		file.close()
	
	if current_dialogues.is_empty():
		current_dialogues = [
			{"speaker": "旁白", "text": "在这片古老的土地上,新的故事即将展开..."},
			{"speaker": "旁白", "text": "你将扮演一个重要的角色,决定这个世界的命运。"},
			{"speaker": "旁白", "text": "准备好开始你的冒险了吗?"}
		]

func _on_continue_pressed() -> void:
	if current_index < current_dialogues.size():
		var line = current_dialogues[current_index]
		speaker_label.text = line.get("speaker", "")
		text_label.text = line.get("text", "")
		current_index += 1
		
		if current_index >= current_dialogues.size():
			continue_button.text = "结束"
			continue_button.pressed.disconnect(_on_continue_pressed)
			continue_button.pressed.connect(_on_game_over)
	else:
		_on_game_over()

func _on_dialogue_started(speaker: String, text: String) -> void:
	speaker_label.text = speaker
	text_label.text = text

func _on_dialogue_ended() -> void:
	text_label.text = "对话结束"

func _on_game_over() -> void:
	get_tree().change_scene_to_file("res://scenes/main.tscn")
'''
        
        (project_path / "scripts" / "game_scene.gd").write_text(script_content, encoding="utf-8")
        print("✓ 游戏场景脚本创建完成")
    
    def _create_game_logic(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建游戏逻辑"""
        characters = analysis.get("analysis", {}).get("characters", [])
        char_names = [char.get("name", "Unknown") for char in characters]
        
        script_content = f'''## 游戏逻辑管理器
extends Node

## 信号
signal game_state_changed(state: String)
signal scene_changed(scene_name: String)

## 游戏状态
var current_scene: String = "main"
var game_data: Dictionary = {{}}
var player_data: Dictionary = {{
\t"name": "玩家",
\t"level": 1,
\t"experience": 0,
\t"inventory": [],
\t"stats": {{
\t\t"strength": 10,
\t\t"dexterity": 10,
\t\t"intelligence": 10
\t}}
}}

## 角色列表
var available_characters: Array = {json.dumps(char_names)}

func _ready() -> void:
\t_load_game_data()

func _load_game_data() -> void:
\t# 加载游戏配置数据
\tvar file = FileAccess.open("user://data/game_config.json", FileAccess.READ)
\tif file:
\t\tvar json = JSON.new()
\t\tvar result = json.parse(file.get_as_text())
\t\tif result == OK:
\t\t\tgame_data = json.data
\t\tfile.close()

func change_scene(scene_name: String) -> void:
\tcurrent_scene = scene_name
\tscene_changed.emit(scene_name)
\tget_tree().change_scene_to_file("res://scenes/" + scene_name + ".tscn")

func add_experience(amount: int) -> void:
\tplayer_data["experience"] += amount
\t# 检查升级
\tvar needed_exp = player_data["level"] * 100
\tif player_data["experience"] >= needed_exp:
\t\tplayer_data["level"] += 1
\t\tplayer_data["experience"] -= needed_exp
\t\tgame_state_changed.emit("level_up")

func add_item(item: Dictionary) -> void:
\tplayer_data["inventory"].append(item)

func has_item(item_name: String) -> bool:
\tfor item in player_data["inventory"]:
\t\tif item.get("name") == item_name:
\t\t\treturn true
\treturn false

func get_character(name: String) -> Dictionary:
\tfor char in game_data.get("characters", []):
\t\tif char.get("name") == name:
\t\t\treturn char
\treturn {{}}

func save_game() -> void:
\tvar file = FileAccess.open("user://save_game.json", FileAccess.WRITE)
\tif file:
\t\tfile.store_string(JSON.stringify(player_data, "\\t"))
\t\tfile.close()

func load_game() -> void:
\tvar file = FileAccess.open("user://save_game.json", FileAccess.READ)
\tif file:
\t\tvar json = JSON.new()
\t\tvar result = json.parse(file.get_as_text())
\t\tif result == OK:
\t\t\tplayer_data = json.data
\t\tfile.close()
'''
        
        (project_path / "scripts" / "game_logic.gd").write_text(script_content, encoding="utf-8")
        print("✓ 游戏逻辑创建完成")
    
    def _create_character_system(self, project_path: Path, analysis: Dict) -> None:
        """创建角色系统"""
        characters = analysis.get("analysis", {}).get("characters", [])
        
        script_content = '''## 角色系统
extends Node
class_name CharacterSystem

## 角色数据
var characters: Dictionary = {}

func _ready() -> void:
\t_init_characters()

func _init_characters() -> void:
'''
        
        for char in characters:
            char_name = char.get("name", "Unknown")
            script_content += f'\tcharacters["{char_name}"] = {json.dumps(char, ensure_ascii=False)}\n'
        
        script_content += '''

func get_character(name: String) -> Dictionary:
\treturn characters.get(name, {})

func get_all_characters() -> Array:
\treturn characters.values()

func update_character(name: String, data: Dictionary) -> void:
\tif characters.has(name):
\t\tcharacters[name].merge(data)
'''
        
        (project_path / "scripts" / "character_system.gd").write_text(script_content, encoding="utf-8")
        print("✓ 角色系统创建完成")
    
    def _create_dialogue_system(self, project_path: Path, analysis: Dict) -> None:
        """创建对话系统"""
        characters = analysis.get("analysis", {}).get("characters", [])
        
        # 为每个角色创建示例对话
        dialogues = {}
        for char in characters:
            char_name = char.get("name", "Unknown")
            dialogues[char_name] = [
                {"speaker": char_name, "text": f"你好，我是{char_name}。"},
                {"speaker": "player", "text": f"你好，{char_name}！"}
            ]
        
        script_content = f'''## 对话系统
extends Node
class_name DialogueSystem

## 信号
signal dialogue_started(speaker: String, text: String)
signal dialogue_ended()
signal choice_made(choice_index: int)

## 对话数据
var dialogues: Dictionary = {json.dumps(dialogues, ensure_ascii=False, indent=2)}
var current_dialogue: Array = []
var current_index: int = 0

func _ready() -> void:
\tpass

func start_dialogue(dialogue_name: String) -> void:
\tif dialogues.has(dialogue_name):
\t\tcurrent_dialogue = dialogues[dialogue_name]
\t\tcurrent_index = 0
\t\t_show_current_line()

func _show_current_line() -> void:
\tif current_index < current_dialogue.size():
\t\tvar line = current_dialogue[current_index]
\t\tdialogue_started.emit(line.get("speaker", ""), line.get("text", ""))
\telse:
\t\tdialogue_ended.emit()

func next_line() -> void:
\tcurrent_index += 1
\t_show_current_line()

func make_choice(choice_index: int) -> void:
\tchoice_made.emit(choice_index)
'''
        
        (project_path / "scripts" / "dialogue_system.gd").write_text(script_content, encoding="utf-8")
        print("✓ 对话系统创建完成")
    
    def _save_analysis_data(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """保存分析数据"""
        # 保存完整分析
        (project_path / "data" / "analysis.json").write_text(
            json.dumps(analysis, ensure_ascii=False, indent=2),
            encoding="utf-8"
        )
        
        # 保存游戏配置
        game_config = {
            "game_type": game_type,
            "analysis": analysis.get("analysis", {}),
            "recommended_types": analysis.get("recommended_types", [])
        }
        (project_path / "data" / "game_config.json").write_text(
            json.dumps(game_config, ensure_ascii=False, indent=2),
            encoding="utf-8"
        )
        
        print("✓ 分析数据保存完成")


def main():
    parser = argparse.ArgumentParser(description="Text2Game - 游戏生成器")
    parser.add_argument("-a", "--analysis", help="分析结果JSON文件路径")
    parser.add_argument("-t", "--type", choices=SUPPORTED_TYPES,
                       help="游戏类型")
    parser.add_argument("-o", "--output", default=DEFAULT_OUTPUT_DIR, help=f"输出目录 (默认: {DEFAULT_OUTPUT_DIR})")
    parser.add_argument("-n", "--name", help="自定义游戏名称")
    parser.add_argument("--no-llm", action="store_true", help="不使用LLM生成分支剧情（使用模板回退）")
    parser.add_argument("--cache-info", action="store_true", help="显示VN生成器缓存信息")
    parser.add_argument("--clear-cache", action="store_true", help="清除VN生成器缓存")
    
    args = parser.parse_args()
    
    # 处理缓存管理命令
    if args.cache_info or args.clear_cache:
        # 动态导入避免循环依赖
        import importlib.util
        _spec = importlib.util.spec_from_file_location(
            "visual_novel",
            Path(__file__).parent / "generators" / "visual_novel.py"
        )
        if _spec and _spec.loader:
            _mod = importlib.util.module_from_spec(_spec)
            _spec.loader.exec_module(_mod)
            VisualNovelGenerator = _mod.VisualNovelGenerator
        else:
            VisualNovelGenerator = None
        
        if VisualNovelGenerator:
            vn_gen = VisualNovelGenerator(args.output)
            
            if args.cache_info:
                info = vn_gen.get_cache_info()
                print(f"VN生成器缓存信息:")
                print(f"  文件数: {info['count']}")
                print(f"  大小: {info['size_human']}")
                print(f"  目录: {info['dir']}")
            
            if args.clear_cache:
                count = vn_gen.clear_cache()
                print(f"已清除 {count} 个缓存文件")
        else:
            print("无法加载VisualNovelGenerator")
        
        return
    
    # 检查必需参数
    if not args.analysis or not args.type:
        parser.error("生成游戏需要 -a/--analysis 和 -t/--type 参数")
    
    # 创建生成器
    generator = GameGenerator(args.output)
    
    # 生成游戏
    try:
        project_path = generator.generate_game(args.analysis, args.type, use_llm=not args.no_llm)
        
        # 如果指定了名称，重命名目录
        if args.name:
            new_path = Path(args.output) / args.name
            if new_path.exists():
                shutil.rmtree(new_path)
            os.rename(project_path, new_path)
            print(f"\n游戏已重命名为: {args.name}")
        
    except FileNotFoundError as e:
        print(f"错误: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"生成失败: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
