#!/usr/bin/env python3
"""
Text2Game - 游戏生成器
基于分析结果生成Godot游戏项目
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional

# 默认配置
DEFAULT_OUTPUT_DIR = "./generated_games"


class GameGenerator:
    """游戏生成器"""
    
    def __init__(self, output_dir: str = DEFAULT_OUTPUT_DIR):
        self.output_dir = Path(output_dir)
    
    def generate_game(self, analysis_file: str, game_type: str, game_config: Optional[Dict] = None) -> str:
        """生成游戏"""
        # 读取分析结果
        analysis_path = Path(analysis_file)
        if not analysis_path.exists():
            raise FileNotFoundError(f"分析文件不存在: {analysis_file}")
        
        analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
        
        # 获取游戏名称
        game_name = self._generate_game_name(analysis, game_type)
        project_path = self.output_dir / game_name
        
        print(f"正在生成游戏: {game_name}")
        print(f"游戏类型: {game_type}")
        print(f"输出路径: {project_path}")
        
        # 创建项目结构
        self._create_project_structure(project_path)
        
        # 生成项目配置
        self._create_project_godot(project_path, analysis, game_type)
        
        # 生成主场景
        self._create_main_scene(project_path, analysis, game_type)
        
        # 生成游戏逻辑
        self._create_game_logic(project_path, analysis, game_type)
        
        # 生成角色系统
        self._create_character_system(project_path, analysis)
        
        # 生成对话系统
        self._create_dialogue_system(project_path, analysis)
        
        # 保存分析数据
        self._save_analysis_data(project_path, analysis, game_type)
        
        print(f"\n✓ 游戏生成完成!")
        print(f"使用以下命令运行游戏:")
        print(f"  godot --path {project_path}")
        
        return str(project_path)
    
    def _generate_game_name(self, analysis: Dict, game_type: str) -> str:
        """生成游戏名称"""
        # 尝试从分析结果获取名称
        world = analysis.get("analysis", {}).get("world", {})
        if world.get("name"):
            name = world["name"]
        else:
            name = "GeneratedGame"
        
        # 清理名称
        name = "".join(c for c in name if c.isalnum() or c in "_- ")
        name = name.replace(" ", "_")
        
        # 添加类型后缀
        return f"{name}_{game_type}"
    
    def _create_project_structure(self, project_path: Path) -> None:
        """创建项目目录结构"""
        dirs = [
            "",
            "scenes",
            "scripts",
            "scripts/scenes",
            "resources",
            "resources/fonts",
            "resources/images",
            "resources/music",
            "resources/sounds",
            "data"
        ]
        
        for dir_name in dirs:
            (project_path / dir_name).mkdir(parents=True, exist_ok=True)
        
        print("✓ 项目结构创建完成")
    
    def _create_project_godot(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建project.godot"""
        game_info = analysis.get("analysis", {}).get("world", {})
        title = game_info.get("name", "Generated Game")
        
        content = f"""; Engine configuration file.
; Generated by Text2Game

config_version=5

[application]

config/name="{title}"
config/description="由Text2Game生成的游戏"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.7", "GL Compatibility")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
"""
        
        (project_path / "project.godot").write_text(content, encoding="utf-8")
        print("✓ project.godot 创建完成")
    
    def _create_main_scene(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建主场景"""
        scene_content = """[gd_scene load_steps=2 format=3 uid="uid://main"]

[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]

[node name="Main" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
script = ExtResource("1_main")

[node name="Background" type="ColorRect" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
color = Color(0.1, 0.1, 0.15, 1)

[node name="VBoxContainer" type="VBoxContainer" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
offset_left = 40.0
offset_top = 40.0
offset_right = -40.0
offset_bottom = -40.0

[node name="Title" type="Label" parent="VBoxContainer"]
layout_mode = 2
text = "游戏标题"
horizontal_alignment = 1
theme_override_font_sizes/font_size = 32

[node name="Content" type="RichTextLabel" parent="VBoxContainer"]
layout_mode = 2
size_flags_vertical = 3
bbcode_enabled = true

[node name="ButtonContainer" type="HBoxContainer" parent="VBoxContainer"]
layout_mode = 2
alignment = 1

[node name="StartButton" type="Button" parent="VBoxContainer/ButtonContainer"]
layout_mode = 2
text = "开始游戏"
"""
        
        (project_path / "scenes" / "main.tscn").write_text(scene_content, encoding="utf-8")
        print("✓ 主场景创建完成")
    
    def _create_game_logic(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """创建游戏逻辑"""
        characters = analysis.get("analysis", {}).get("characters", [])
        char_names = [char.get("name", "Unknown") for char in characters]
        
        script_content = f'''## 游戏逻辑管理器
extends Node

## 信号
signal game_state_changed(state: String)
signal scene_changed(scene_name: String)

## 游戏状态
var current_scene: String = "main"
var game_data: Dictionary = {{}}
var player_data: Dictionary = {{
\t"name": "玩家",
\t"level": 1,
\t"experience": 0,
\t"inventory": [],
\t"stats": {{
\t\t"strength": 10,
\t\t"dexterity": 10,
\t\t"intelligence": 10
\t}}
}}

## 角色列表
var available_characters: Array = {json.dumps(char_names)}

func _ready() -> void:
\t_load_game_data()

func _load_game_data() -> void:
\t# 加载游戏配置数据
\tvar file = FileAccess.open("user://data/game_config.json", FileAccess.READ)
\tif file:
\t\tvar json = JSON.new()
\t\tvar result = json.parse(file.get_as_text())
\t\tif result == OK:
\t\t\tgame_data = json.data
\t\tfile.close()

func change_scene(scene_name: String) -> void:
\tcurrent_scene = scene_name
\tscene_changed.emit(scene_name)
\tget_tree().change_scene_to_file("res://scenes/" + scene_name + ".tscn")

func add_experience(amount: int) -> void:
\tplayer_data["experience"] += amount
\t# 检查升级
\tvar needed_exp = player_data["level"] * 100
\tif player_data["experience"] >= needed_exp:
\t\tplayer_data["level"] += 1
\t\tplayer_data["experience"] -= needed_exp
\t\tgame_state_changed.emit("level_up")

func add_item(item: Dictionary) -> void:
\tplayer_data["inventory"].append(item)

func has_item(item_name: String) -> bool:
\tfor item in player_data["inventory"]:
\t\tif item.get("name") == item_name:
\t\t\treturn true
\treturn false

func get_character(name: String) -> Dictionary:
\tfor char in game_data.get("characters", []):
\t\tif char.get("name") == name:
\t\t\treturn char
\treturn {{}}

func save_game() -> void:
\tvar file = FileAccess.open("user://save_game.json", FileAccess.WRITE)
\tif file:
\t\tfile.store_string(JSON.stringify(player_data, "\\t"))
\t\tfile.close()

func load_game() -> void:
\tvar file = FileAccess.open("user://save_game.json", FileAccess.READ)
\tif file:
\t\tvar json = JSON.new()
\t\tvar result = json.parse(file.get_as_text())
\t\tif result == OK:
\t\t\tplayer_data = json.data
\t\tfile.close()
'''
        
        (project_path / "scripts" / "game_logic.gd").write_text(script_content, encoding="utf-8")
        print("✓ 游戏逻辑创建完成")
    
    def _create_character_system(self, project_path: Path, analysis: Dict) -> None:
        """创建角色系统"""
        characters = analysis.get("analysis", {}).get("characters", [])
        
        script_content = '''## 角色系统
extends Node
class_name CharacterSystem

## 角色数据
var characters: Dictionary = {}

func _ready() -> void:
\t_init_characters()

func _init_characters() -> void:
'''
        
        for char in characters:
            char_name = char.get("name", "Unknown")
            script_content += f'\tcharacters["{char_name}"] = {json.dumps(char, ensure_ascii=False)}\n'
        
        script_content += '''

func get_character(name: String) -> Dictionary:
\treturn characters.get(name, {})

func get_all_characters() -> Array:
\treturn characters.values()

func update_character(name: String, data: Dictionary) -> void:
\tif characters.has(name):
\t\tcharacters[name].merge(data)
'''
        
        (project_path / "scripts" / "character_system.gd").write_text(script_content, encoding="utf-8")
        print("✓ 角色系统创建完成")
    
    def _create_dialogue_system(self, project_path: Path, analysis: Dict) -> None:
        """创建对话系统"""
        characters = analysis.get("analysis", {}).get("characters", [])
        
        # 为每个角色创建示例对话
        dialogues = {}
        for char in characters:
            char_name = char.get("name", "Unknown")
            dialogues[char_name] = [
                {"speaker": char_name, "text": f"你好，我是{char_name}。"},
                {"speaker": "player", "text": f"你好，{char_name}！"}
            ]
        
        script_content = f'''## 对话系统
extends Node
class_name DialogueSystem

## 信号
signal dialogue_started(speaker: String, text: String)
signal dialogue_ended()
signal choice_made(choice_index: int)

## 对话数据
var dialogues: Dictionary = {json.dumps(dialogues, ensure_ascii=False, indent=2)}
var current_dialogue: Array = []
var current_index: int = 0

func _ready() -> void:
\tpass

func start_dialogue(dialogue_name: String) -> void:
\tif dialogues.has(dialogue_name):
\t\tcurrent_dialogue = dialogues[dialogue_name]
\t\tcurrent_index = 0
\t\t_show_current_line()

func _show_current_line() -> void:
\tif current_index < current_dialogue.size():
\t\tvar line = current_dialogue[current_index]
\t\tdialogue_started.emit(line.get("speaker", ""), line.get("text", ""))
\telse:
\t\tdialogue_ended.emit()

func next_line() -> void:
\tcurrent_index += 1
\t_show_current_line()

func make_choice(choice_index: int) -> void:
\tchoice_made.emit(choice_index)
'''
        
        (project_path / "scripts" / "dialogue_system.gd").write_text(script_content, encoding="utf-8")
        print("✓ 对话系统创建完成")
    
    def _save_analysis_data(self, project_path: Path, analysis: Dict, game_type: str) -> None:
        """保存分析数据"""
        # 保存完整分析
        (project_path / "data" / "analysis.json").write_text(
            json.dumps(analysis, ensure_ascii=False, indent=2),
            encoding="utf-8"
        )
        
        # 保存游戏配置
        game_config = {
            "game_type": game_type,
            "analysis": analysis.get("analysis", {}),
            "recommended_types": analysis.get("recommended_types", [])
        }
        (project_path / "data" / "game_config.json").write_text(
            json.dumps(game_config, ensure_ascii=False, indent=2),
            encoding="utf-8"
        )
        
        print("✓ 分析数据保存完成")


def main():
    parser = argparse.ArgumentParser(description="Text2Game - 游戏生成器")
    parser.add_argument("-a", "--analysis", required=True, help="分析结果JSON文件路径")
    parser.add_argument("-t", "--type", required=True, choices=["rpg", "adventure", "visual_novel", "strategy", "action"],
                       help="游戏类型")
    parser.add_argument("-o", "--output", default=DEFAULT_OUTPUT_DIR, help=f"输出目录 (默认: {DEFAULT_OUTPUT_DIR})")
    parser.add_argument("-n", "--name", help="自定义游戏名称")
    
    args = parser.parse_args()
    
    # 创建生成器
    generator = GameGenerator(args.output)
    
    # 生成游戏
    try:
        project_path = generator.generate_game(args.analysis, args.type)
        
        # 如果指定了名称，重命名目录
        if args.name:
            new_path = Path(args.output) / args.name
            if new_path.exists():
                shutil.rmtree(new_path)
            os.rename(project_path, new_path)
            print(f"\n游戏已重命名为: {args.name}")
        
    except FileNotFoundError as e:
        print(f"错误: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"生成失败: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
