## Game Generator - 游戏生成器
extends Node
class_name GameGenerator

## 信号
signal game_generated(project_path: String)
signal generation_progress(step: String, progress: float)
signal generation_failed(error: String)

## 引用
var llm_client: LLMClient

## 生成配置
var output_dir: String = "user://generated_games/"

func _ready() -> void:
	llm_client = LLMClient.new()
	add_child(llm_client)
	llm_client.response_received.connect(_on_llm_response)
	llm_client.error_occurred.connect(_on_llm_error)

## 生成完整游戏
func generate_game(text: String, analysis: Dictionary, game_type: String, game_config: Dictionary) -> void:
	var game_name = game_config.get("game_info", {}).get("title", "generated_game")
	var project_path = output_dir + game_name
	
	# 创建目录结构
	_create_project_structure(project_path)
	
	generation_progress.emit("创建项目配置", 0.1)
	_create_project_godot(project_path, game_config)
	
	generation_progress.emit("生成主场景", 0.2)
	_create_main_scene(project_path, game_config, game_type)
	
	generation_progress.emit("生成主脚本", 0.25)
	_create_main_script(project_path, game_config, game_type)
	
	generation_progress.emit("生成角色系统", 0.3)
	_create_character_system(project_path, game_config)
	
	generation_progress.emit("生成对话系统", 0.4)
	_create_dialogue_system(project_path, game_config)
	
	generation_progress.emit("生成游戏场景", 0.5)
	_create_game_scene(project_path, game_config, game_type)
	
	generation_progress.emit("生成游戏场景脚本", 0.55)
	_create_game_scene_script(project_path, game_config, game_type)
	
	generation_progress.emit("生成额外场景", 0.6)
	_create_game_scenes(project_path, game_config, game_type)
	
	generation_progress.emit("生成UI系统", 0.65)
	_create_ui_system(project_path, game_config)
	
	generation_progress.emit("生成游戏逻辑", 0.7)
	_create_game_logic(project_path, game_config, game_type)
	
	generation_progress.emit("生成资源文件", 0.8)
	_create_resources(project_path, game_config)
	
	generation_progress.emit("保存游戏数据", 0.9)
	_save_game_data(project_path, text, analysis, game_config)
	
	generation_progress.emit("完成", 1.0)
	game_generated.emit(project_path)

## 创建项目目录结构
func _create_project_structure(project_path: String) -> void:
	var dirs = [
		"",
		"scenes",
		"scripts",
		"resources",
		"resources/fonts",
		"resources/images",
		"resources/music",
		"resources/sounds",
		"data"
	]
	
	for dir in dirs:
		var full_path = project_path + "/" + dir
		DirAccess.make_dir_recursive_absolute(full_path)

## 创建project.godot
func _create_project_godot(project_path: String, config: Dictionary) -> void:
	var game_info = config.get("game_info", {})
	var content = """; Engine configuration file.
; Generated by Text2Game

config_version=5

[application]

config/name="%s"
config/description="%s"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.7", "GL Compatibility")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
window/stretch/mode="canvas_items"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
""" % [game_info.get("title", "Generated Game"), game_info.get("description", "A game generated by Text2Game")]
	
	_save_file(project_path + "/project.godot", content)

## 创建主场景
func _create_main_scene(project_path: String, config: Dictionary, game_type: String) -> void:
	var scene_content = """[gd_scene load_steps=2 format=3 uid="uid://main"]

[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]

[node name="Main" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
script = ExtResource("1_main")

[node name="Background" type="ColorRect" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
color = Color(0.1, 0.1, 0.15, 1)

[node name="VBoxContainer" type="VBoxContainer" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
offset_left = 40.0
offset_top = 40.0
offset_right = -40.0
offset_bottom = -40.0

[node name="Title" type="Label" parent="VBoxContainer"]
layout_mode = 2
text = "%s"
horizontal_alignment = 1

[node name="Content" type="RichTextLabel" parent="VBoxContainer"]
layout_mode = 2
size_flags_vertical = 3
bbcode_enabled = true

[node name="ButtonContainer" type="HBoxContainer" parent="VBoxContainer"]
layout_mode = 2
alignment = 1

[node name="StartButton" type="Button" parent="VBoxContainer/ButtonContainer"]
layout_mode = 2
text = "开始游戏"
""" % config.get("game_info", {}).get("title", "Game")
	
	_save_file(project_path + "/scenes/main.tscn", scene_content)

## 创建游戏场景
func _create_game_scene(project_path: String, config: Dictionary, game_type: String) -> void:
	var scene_content = """[gd_scene load_steps=2 format=3 uid="uid://game_scene"]

[ext_resource type="Script" path="res://scripts/game_scene.gd" id="1_script"]

[node name="Game" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
script = ExtResource("1_script")

[node name="Background" type="ColorRect" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
color = Color(0.08, 0.08, 0.12, 1)

[node name="VBoxContainer" type="VBoxContainer" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
offset_left = 40.0
offset_top = 40.0
offset_right = -40.0
offset_bottom = -40.0

[node name="SpeakerLabel" type="Label" parent="VBoxContainer"]
layout_mode = 2
text = ""
theme_override_font_sizes/font_size = 24
theme_override_colors/font_color = Color(0.9, 0.9, 1.0, 1)

[node name="DialogueBox" type="PanelContainer" parent="VBoxContainer"]
layout_mode = 2
size_flags_vertical = 3

[node name="VBox" type="VBoxContainer" parent="VBoxContainer/DialogueBox"]
layout_mode = 2

[node name="TextLabel" type="RichTextLabel" parent="VBoxContainer/DialogueBox/VBox"]
layout_mode = 2
size_flags_vertical = 3
bbcode_enabled = true
text = ""

[node name="ChoicesContainer" type="VBoxContainer" parent="VBoxContainer"]
layout_mode = 2

[node name="ContinueButton" type="Button" parent="VBoxContainer"]
layout_mode = 2
text = "继续"
custom_minimum_size = Vector2(200, 40)
"""
	_save_file(project_path + "/scenes/game.tscn", scene_content)

## 创建游戏场景脚本
func _create_game_scene_script(project_path: String, config: Dictionary, game_type: String) -> void:
	var game_info = config.get("game_info", {})
	var script_content = """## 游戏场景控制器
extends Control

## 组件引用
@onready var speaker_label = $VBoxContainer/SpeakerLabel
@onready var text_label = $VBoxContainer/DialogueBox/VBox/TextLabel
@onready var choices_container = $VBoxContainer/ChoicesContainer
@onready var continue_button = $VBoxContainer/ContinueButton

## 系统引用
var dialogue_system: Node
var character_system: Node
var game_logic: Node

## 当前对话数据
var current_dialogues: Array = []
var current_index: int = 0

func _ready() -> void:
	# 获取系统引用
	dialogue_system = _find_system("DialogueSystem")
	character_system = _find_system("CharacterSystem")
	game_logic = _find_system("GameLogic")
	
	# 连接信号
	continue_button.pressed.connect(_on_continue_pressed)
	
	if dialogue_system:
		dialogue_system.dialogue_started.connect(_on_dialogue_started)
		dialogue_system.dialogue_ended.connect(_on_dialogue_ended)
	
	# 开始游戏
	_start_game()

func _find_system(system_name: String) -> Node:
	for child in get_parent().get_children():
		if child.get_script() and child.get_script().get_global_name() == system_name:
			return child
	for child in get_children():
		if child.get_script() and child.get_script().get_global_name() == system_name:
			return child
	return null

func _start_game() -> void:
	_load_dialogues()
	
	speaker_label.text = "旁白"
	text_label.text = "欢迎来到游戏世界！\n\n点击[继续]开始冒险..."
	continue_button.visible = true

func _load_dialogues() -> void:
	var file = FileAccess.open("user://data/game_config.json", FileAccess.READ)
	if file:
		var json = JSON.new()
		var result = json.parse(file.get_as_text())
		if result == OK:
			var config_data = json.data
			current_dialogues = config_data.get("dialogues", {}).get("main", [])
		file.close()
	
	if current_dialogues.is_empty():
		current_dialogues = [
			{"speaker": "旁白", "text": "在这片古老的土地上，新的故事即将展开..."},
			{"speaker": "旁白", "text": "你将扮演一个重要的角色，决定这个世界的命运。"},
			{"speaker": "旁白", "text": "准备好开始你的冒险了吗？"}
		]

func _on_continue_pressed() -> void:
	if current_index < current_dialogues.size():
		var line = current_dialogues[current_index]
		speaker_label.text = line.get("speaker", "")
		text_label.text = line.get("text", "")
		current_index += 1
		
		if current_index >= current_dialogues.size():
			continue_button.text = "结束"
			continue_button.pressed.disconnect(_on_continue_pressed)
			continue_button.pressed.connect(_on_game_over)
	else:
		_on_game_over()

func _on_dialogue_started(speaker: String, text: String) -> void:
	speaker_label.text = speaker
	text_label.text = text

func _on_dialogue_ended() -> void:
	text_label.text = "对话结束"

func _on_game_over() -> void:
	get_tree().change_scene_to_file("res://scenes/main.tscn")
"""
	_save_file(project_path + "/scripts/game_scene.gd", script_content)

## 创建角色系统
func _create_character_system(project_path: String, config: Dictionary) -> void:
	var characters = config.get("characters", [])
	var script_content = """## 角色系统
extends Node
class_name CharacterSystem

## 角色数据
var characters: Dictionary = {}

func _ready() -> void:
	_init_characters()

func _init_characters() -> void:
"""
	for char in characters:
		var char_name = char.get("name", "Unknown")
		var char_data = JSON.stringify(char, "\t")
		script_content += '\tcharacters["%s"] = %s\n' % [char_name, char_data]
	
	script_content += """

func get_character(name: String) -> Dictionary:
	return characters.get(name, {})

func get_all_characters() -> Array:
	return characters.values()

func update_character(name: String, data: Dictionary) -> void:
	if characters.has(name):
		characters[name].merge(data)
"""
	_save_file(project_path + "/scripts/character_system.gd", script_content)

## 创建对话系统
func _create_dialogue_system(project_path: String, config: Dictionary) -> void:
	var dialogues = config.get("dialogues", {})
	var script_content = """## 对话系统
extends Node
class_name DialogueSystem

## 信号
signal dialogue_started(speaker: String, text: String)
signal dialogue_ended()
signal choice_made(choice_index: int)

## 对话数据
var dialogues: Dictionary = {}
var current_dialogue: Array = []
var current_index: int = 0

func _ready() -> void:
	_init_dialogues()

func _init_dialogues() -> void:
"""
	# 添加对话数据
	for key in dialogues:
		var dialogue_data = JSON.stringify(dialogues[key], "\t")
		script_content += '\tdialogues["%s"] = %s\n' % [key, dialogue_data]
	
	script_content += """

func start_dialogue(dialogue_name: String) -> void:
	if dialogues.has(dialogue_name):
		current_dialogue = dialogues[dialogue_name]
		current_index = 0
		_show_current_line()

func _show_current_line() -> void:
	if current_index < current_dialogue.size():
		var line = current_dialogue[current_index]
		dialogue_started.emit(line.get("speaker", ""), line.get("text", ""))
	else:
		dialogue_ended.emit()

func next_line() -> void:
	current_index += 1
	_show_current_line()

func make_choice(choice_index: int) -> void:
	choice_made.emit(choice_index)
"""
	_save_file(project_path + "/scripts/dialogue_system.gd", script_content)

## 创建游戏场景
func _create_game_scenes(project_path: String, config: Dictionary, game_type: String) -> void:
	var scenes = config.get("scenes", [])
	for scene in scenes:
		var scene_name = scene.get("name", "scene")
		var scene_content = """[gd_scene load_steps=2 format=3 uid="uid://%s"]

[ext_resource type="Script" path="res://scripts/scenes/%s.gd" id="1_script"]

[node name="%s" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
script = ExtResource("1_script")

[node name="Background" type="ColorRect" parent="."]
layout_mode = 1
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0

[node name="Label" type="Label" parent="."]
layout_mode = 1
anchors_preset = 8
anchor_left = 0.5
anchor_top = 0.5
anchor_right = 0.5
anchor_bottom = 0.5
text = "%s"
""" % [scene_name, scene_name, scene_name, scene.get("description", scene_name)]
		
		_save_file(project_path + "/scenes/%s.tscn" % scene_name, scene_content)
		
		# 创建场景脚本
		var script_content = """## %s 场景脚本
extends Control

func _ready() -> void:
	pass

func _process(delta: float) -> void:
	pass
""" % scene_name
		
		_save_file(project_path + "/scripts/scenes/%s.gd" % scene_name, script_content)

## 创建UI系统
func _create_ui_system(project_path: String, config: Dictionary) -> void:
	var ui_script = """## UI系统
extends CanvasLayer

## 信号
signal button_pressed(button_name: String)

## UI元素引用
@onready var dialogue_box = $DialogueBox
@onready var name_label = $DialogueBox/VBox/NameLabel
@onready var text_label = $DialogueBox/VBox/TextLabel
@onready var choices_container = $DialogueBox/VBox/ChoicesContainer

func _ready() -> void:
	_hide_dialogue()

func show_dialogue(speaker: String, text: String, choices: Array = []) -> void:
	dialogue_box.visible = true
	name_label.text = speaker
	text_label.text = text
	
	# 清除旧选项
	for child in choices_container.get_children():
		child.queue_free()
	
	# 添加新选项
	for i in range(choices.size()):
		var button = Button.new()
		button.text = choices[i]
		button.pressed.connect(_on_choice_pressed.bind(i))
		choices_container.add_child(button)

func _hide_dialogue() -> void:
	dialogue_box.visible = false

func _on_choice_pressed(index: int) -> void:
	button_pressed.emit("choice_" + str(index))
	_hide_dialogue()

func show_notification(text: String, duration: float = 2.0) -> void:
	# 显示通知
	pass
"""
	_save_file(project_path + "/scripts/ui_system.gd", ui_script)

## 创建游戏逻辑
func _create_game_logic(project_path: String, config: Dictionary, game_type: String) -> void:
	var game_logic = """## 游戏逻辑管理器
extends Node

## 信号
signal game_state_changed(state: String)
signal scene_changed(scene_name: String)

## 游戏状态
var current_scene: String = "main"
var game_data: Dictionary = {}
var player_data: Dictionary = {
	"name": "玩家",
	"level": 1,
	"experience": 0,
	"inventory": [],
	"stats": {
		"strength": 10,
		"dexterity": 10,
		"intelligence": 10
	}
}

func _ready() -> void:
	_load_game_data()

func _load_game_data() -> void:
	# 加载游戏配置数据
	var file = FileAccess.open("user://data/game_config.json", FileAccess.READ)
	if file:
		var json = JSON.new()
		var result = json.parse(file.get_as_text())
		if result == OK:
			game_data = json.data
		file.close()

func change_scene(scene_name: String) -> void:
	current_scene = scene_name
	scene_changed.emit(scene_name)
	get_tree().change_scene_to_file("res://scenes/%s.tscn" % scene_name)

func add_experience(amount: int) -> void:
	player_data["experience"] += amount
	# 检查升级
	var needed_exp = player_data["level"] * 100
	if player_data["experience"] >= needed_exp:
		player_data["level"] += 1
		player_data["experience"] -= needed_exp
		game_state_changed.emit("level_up")

func add_item(item: Dictionary) -> void:
	player_data["inventory"].append(item)

func has_item(item_name: String) -> bool:
	for item in player_data["inventory"]:
		if item.get("name") == item_name:
			return true
	return false

func save_game() -> void:
	var file = FileAccess.open("user://save_game.json", FileAccess.WRITE)
	if file:
		file.store_string(JSON.stringify(player_data, "\t"))
		file.close()

func load_game() -> void:
	var file = FileAccess.open("user://save_game.json", FileAccess.READ)
	if file:
		var json = JSON.new()
		var result = json.parse(file.get_as_text())
		if result == OK:
			player_data = json.data
		file.close()
"""
	_save_file(project_path + "/scripts/game_logic.gd", game_logic)

## 创建资源文件
func _create_resources(project_path: String, config: Dictionary) -> void:
	# 创建主题
	var theme_content = """[gd_resource type="Theme" format=3]

[resource]
default_font_size = 16
"""
	_save_file(project_path + "/resources/default_theme.tres", theme_content)
	
	# 创建占位图片说明
	var readme = """# 资源文件

将你的游戏资源放在此目录:

- fonts/ - 字体文件
- images/ - 图片资源
- music/ - 背景音乐
- sounds/ - 音效文件

## 推荐格式
- 图片: PNG (带透明通道) 或 JPG
- 音乐: OGG Vorbis
- 音效: OGG 或 WAV
- 字体: TTF 或 OTF
"""
	_save_file(project_path + "/resources/README.md", readme)

## 保存游戏数据
func _save_game_data(project_path: String, text: String, analysis: Dictionary, config: Dictionary) -> void:
	# 保存原始文本
	_save_file(project_path + "/data/original_text.txt", text)
	
	# 保存分析结果
	_save_file(project_path + "/data/analysis.json", JSON.stringify(analysis, "\t"))
	
	# 保存游戏配置
	_save_file(project_path + "/data/game_config.json", JSON.stringify(config, "\t"))

## 创建主脚本
func _create_main_script(project_path: String, config: Dictionary, game_type: String) -> void:
	var game_info = config.get("game_info", {})
	var script_content = """## 主场景控制器
extends Control

## 系统引用
var game_logic: Node
var dialogue_system: Node
var character_system: Node

## 组件引用
@onready var title_label = $VBoxContainer/Title
@onready var content_label = $VBoxContainer/Content
@onready var start_button = $VBoxContainer/ButtonContainer/StartButton

func _ready() -> void:
	# 初始化系统
	character_system = preload("res://scripts/character_system.gd").new()
	add_child(character_system)
	
	dialogue_system = preload("res://scripts/dialogue_system.gd").new()
	add_child(dialogue_system)
	
	game_logic = preload("res://scripts/game_logic.gd").new()
	add_child(game_logic)
	
	# 连接信号
	dialogue_system.dialogue_started.connect(_on_dialogue_started)
	dialogue_system.dialogue_ended.connect(_on_dialogue_ended)
	
	# 初始化UI
	title_label.text = game_info.get("title", "游戏")
	content_label.text = game_info.get("description", "欢迎来到游戏世界！")
	
	# 连接按钮
	start_button.pressed.connect(_on_start_button_pressed)

func _on_start_button_pressed() -> void:
	# 开始游戏
	game_logic.change_scene("game")

func _on_dialogue_started(speaker: String, text: String) -> void:
	content_label.text = "[b]%s[/b]\n%s" % [speaker, text]

func _on_dialogue_ended() -> void:
	content_label.text = "游戏结束"
"""
	_save_file(project_path + "/scripts/main.gd", script_content)

## 保存文件辅助函数
func _save_file(path: String, content: String) -> void:
	var file = FileAccess.open(path, FileAccess.WRITE)
	if file:
		file.store_string(content)
		file.close()
	else:
		generation_failed.emit("无法创建文件: " + path)

## 响应处理
func _on_llm_response(response: Dictionary) -> void:
	# 处理LLM响应
	pass

func _on_llm_error(error: String) -> void:
	generation_failed.emit(error)

## 获取生成的游戏路径
func get_game_path(game_name: String) -> String:
	return output_dir + game_name
